#!/usr/bin/with-contenv bash

set -e

export SENDFILE=0

cd /opt/service

exec pipenv run $( [ "${USE_DDTRACE_RUN:-true}"  = "true" ] && printf '%s' 'ddtrace-run' || true ) gunicorn \
    wsgi \
    --bind 0.0.0.0:80 \
    --access-logfile - \
    --error-logfile - \
    --log-level "${LOG_LEVEL:-debug}" \
    --worker-class gevent \
    --max-requests 50 \
    $( [ "${ENV:-dev}"  = "local" ] && printf '%s' '--reload' || true ) \
    $( [ "${ENV:-dev}"  = "local" ] && printf '%s' '--reload-engine auto' || true ) \
    $( [ "${ENV:-dev}" != "local" ] && printf '%s' '--workers 30' || printf '%s' '--workers 10' ) \
    --timeout 300 \
    --graceful-timeout 300 \
    --keep-alive 300 \
    --logger-class "$LOGGER_CLASS"
